### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by XionioXMaster** [MeidoNoHitsuji/DiscordAuthSystem_module#1]
Привет, я по поводу   **"redirectUrl": "это редирект, который вы указали",**
Не понимаю о чём идет речь и что туда нужно указать, можно поподробнее об этом?

**Comment by rezraf** [comment]
то, что было указано в редиректах настройки дискорда

**Comment by MeidoNoHitsuji** [comment]
Смотрите 3 пункт установки модуля.
