### ISSUE TITLE
gradle wrapper

### ISSUE THREAD

**Issue by TuskarMA** [MeidoNoHitsuji/DiscordAuthSystem_module#3]
Привет. Почти не пишу на Java. Просидел 10 часов пытаясь понять какую версию gradle надо использовать, чтобы собрать wrapper и забилдить джарник из сурса. Модуль классный, но хотелось бы переделать его чуток под себя. К примеру, переписать под монгу вместо SQL, добавить дизайны страниц и т.п.

Пробовал:
6.8
7.0
7.3.3
7.4
7.5
7.6.1
8.1
Все безуспешно)

**Comment by MeidoNoHitsuji** [comment]
Вполне возможно что модуль уже устарел, т.к. я не обновлял его до более новых версий

**Comment by TuskarMA** [comment]
> Вполне возможно что модуль уже устарел, т.к. я не обновлял его до более новых версий

Да нет, вроде бы как работает, при чем очень даже неплохо) Патч для рантайма правда дружиться не очень хотел с новым рантаймом, но если руками пройтись, то даже с ним все хорошо. 
А с Gradle и Gradle wrapper скорее всего проблемы из-за моей криворукости и навыков работы с билдерами на java, поэтому скорее хочу уточнить порядок действий, а не указать об ошибке)

**Comment by TuskarMA** [comment]
Спустя 15 часов ликбеза додумался собрать все через wrapper лаунчсервера. Вопрос закрыт. Все работает, единственной проблемой была моя тупость в Java
